# SPDX-FileCopyrightText: 2022 Paul Ritter <ritter.paul1@googlemail.com>
# SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Svarshik <96281939+lexaSvarshik@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 nazrin <tikufaev@outlook.com>
#
# SPDX-License-Identifier: MIT

name: No submodule update checker

on:
  pull_request:
    paths:
      - 'SupermatterEngine'  # Reserve edit

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  this_aint_right:
    name: Submodule update in pr found
    runs-on: ubuntu-latest
    steps:
      - name: Fail
        run: exit 1
